language: ruby
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        # remove default pyenv
        - sudo rm -rf $(pyenv root)
        # remove postgresql ppa to install ubuntu-make
        - sudo rm -rf /etc/apt/sources.list.d/pgdg.list
        - sudo apt update
    - os: osx
      osx_image: xcode12.5
install:
  - gem install bundler
script:
  - chmod 0755 ./bin/install.sh
  - DOTFILES_HOME=~/kobanyan/dotfiles ./bin/install.sh
  - cd test
  - bundle install
  - bundle exec rspec
