FISHER_PLUGINS=(
  decors/fish-ghq
  IlanCosman/tide
  jethrokuan/fzf
  jethrokuan/z
  jorgebucaran/fisher
  kobanyan/tide-asdf-items
  kobanyan/pet-completions
  laughedelic/pisces
  oh-my-fish/plugin-thefuck
  sijad/gitignore
)
